version: '3.2'

# Use the default driver (here bridge)
networks:
  priv:
  pub:

services:

  db:
    environment:
      - PGDATA=/beacon-db
      - POSTGRES_USER=beacon
      - POSTGRES_PASSWORD=secretpassword
      - POSTGRES_DB=beacon
    hostname: beacon-db
    container_name: beacon-db
    image: postgres:9.6-alpine
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    networks:
      - priv

  beacon:
    build: ../src
    image: egarchive/beacon-api:2.0
    hostname: beacon
    container_name: beacon
    environment:
      - DATABASE_URL=beacon-db
      - DATABASE_PORT=5432
      - DATABASE_USER=beacon
      - DATABASE_PASSWORD=secretpassword
      - DATABASE_NAME=beacon
      - DATABASE_SCHEMA=public
    volumes:
      - ./beacon/beacon.conf:/beacon/beacon_api/conf/config.ini
      - ./beacon/access_levels.yml:/beacon/beacon_api/utils/access_levels.yml
    ports:
      - "5050:5050"
    networks:
      - priv
      - pub

  ui:
    build: ../ui
    image: egarchive/beacon-ui:2.0
    hostname: beacon-ui
    container_name: beacon-ui
    environment:
      - BEACON_UI_CONF=/beacon/conf.ini
    volumes:
      - ./beacon/ui.conf:/beacon/conf.ini
      - ../ui/static:/beacon/static
      - ../ui/templates:/beacon/templates
      - ./beacon/beacon_project_small.png:/beacon/static/logo.png
    ports:
      - "8000:8000"
    networks:
      - pub
