version: '3.2'

# Use the default driver (here bridge)
networks:
  priv:
  pub:

services:

  db:
    environment:
      - PGDATA=/beacon-db
      - POSTGRES_USER=beacon
      - POSTGRES_PASSWORD=secretpassword
      - POSTGRES_DB=beacon
    hostname: beacon-db
    container_name: beacon-db
    image: postgres:12-alpine
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - "5049:5432"  # Only for development: connect to the db from outside the Docker container
    networks:
      - priv

  beacon:
    build: ..
    image: egarchive/beacon:2.0
    hostname: beacon
    container_name: beacon
    volumes:
      - ../beacon:/beacon/beacon  # inject the code, so we see the modifications "live"
      - ./conf.py:/beacon/beacon/conf.py
      - ./access_levels.yml:/beacon/beacon/utils/access_levels.yml
    ports:
      - "5050:5050"
    networks:
      - priv
      - pub
    # entrypoint: ['/bin/sleep','100000000']  # we don't run the beacon just after starting, we'll do it manually 

  # ui:
  #   build: ../ui
  #   image: egarchive/beacon-ui:2.0
  #   hostname: beacon-ui
  #   container_name: beacon-ui
  #   environment:
  #     - BEACON_UI_CONF=/beacon/conf.ini
  #   volumes:
  #     - ./beacon/ui.conf:/beacon/conf.ini
  #     - ../ui/beaconui:/beacon/beaconui   # we do that to be able to modify the code and update the container "live"
  #     - ../ui/static:/beacon/static
  #     - ../ui/templates:/beacon/templates
  #     - ./logo.png:/beacon/static/logo.png
  #   ports:
  #     - "8000:8000"
  #   networks:
  #     - pub
