version: '3.1'

networks:
  beacon-priv:
  idp-priv:
  pub:
  my-app-network:
    external: true

services:

  ###########################################
  # MongoDB Database
  ###########################################

  db-images:
    image: mongo:5
    command: mongod --port 27019
    hostname: mongo
    ports:
      - 27019:27019
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: beacon
    volumes:
      - ./mongo-init/:/docker-entrypoint-initdb.d/:ro
    networks:
      - beacon-priv
      - my-app-network


  mongo-express-images:
    image: mongo-express
    restart: always
    ports:
      - 8084:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27019/
    networks:
      - beacon-priv

  ###########################################
  # Beacon
  ###########################################

  beacon-images:
    build: ..
    image: egarchive/beacon:2.0
    hostname: beacon-images
    container_name: beacon-images
    volumes:
      # - ../beacon:/beacon/beacon  # inject the code, so we see the modifications "live"
      # - ../ui/static:/beacon/ui/static
      # - ../ui/templates:/beacon/ui/templates
      - ./conf.py:/beacon/beacon/conf.py
      - ./logger.yml:/beacon/beacon/logger.yml
      - ./ontologies:/beacon/ontologies
    ports:
      - "5054:5050"
    networks:
      - beacon-priv
      - pub
      - idp-priv
      - my-app-network
    working_dir: '/beacon'
    entrypoint: ['python','-m','beacon']
    # entrypoint: ['/bin/sleep','100000000']

  ###########################################
  # Dummy Permissions server
  ###########################################
  
  permissions-images:
    image: egarchive/beacon:2.0
    hostname: beacon-permissions-images
    container_name: beacon-permissions-images
    volumes:
      - ../permissions/:/beacon/permissions/  # inject the code, so we see the modifications "live"
      - ./logger.yml:/beacon/logger.yml
    ports:
      - "5055:5051"
    networks:
      - beacon-priv
      - pub
      - idp-priv
      - my-app-network
    #entrypoint: ['/bin/sleep','100000000']
    working_dir: '/beacon'
    entrypoint: ['python','-m', 'permissions']

  frontend-images:
    build:
      context: ../frontend-images
    command: node /opt/yarn-v1.22.19/bin/yarn.js start
    container_name: react-images
    depends_on:
      - beacon-images
    ports:
      - 3004:3001
    volumes:
      - ../frontend-images/.env:/frontend/.env
      - ../frontend-images/src/config.json:/frontend/src/config.json

