name: "Testsuite"

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - 'tests'
      - 'tests/*'
      - 'refactoring'

jobs:
  testsuite:
    strategy:
      max-parallel: 4
      matrix:
        # os: [ubuntu-latest, macOS-latest]
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    name: Beacon (v2.x) API tests

    steps:
    - uses: actions/checkout@master
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@master
      with:
        python-version: 3.6
    - name: (re)Build docker images
      run: |
        pushd deploy
        docker-compose build beacon
        popd
    - name: Install required tools
      run: |
        git clone https://github.com/bats-core/bats-core.git
        pushd bats-core
        git checkout v1.1.0
        sudo ./install.sh /usr/local
        popd
        rm -rf bats-core
        sudo apt-get install curl jq git-lfs
        sudo -- bash -c -e "echo '127.0.0.1    idp beacon beacon-permissions' >> /etc/hosts"
    - name: Bootstrap a Beacon
      run: |
        pushd deploy
        git lfs install
        git lfs fetch
        docker-compose up -d db
        sleep 30
        docker-compose up -d
        docker-compose ps
        docker-compose logs
        popd
    - name: Running testsuite
      run: bats tests
    - name: Cleanup
      run: |
        pushd deploy
        docker-compose down -v
        popd


